manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/kiwikey
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: dev_test01
      import: app/west.yml
  self:
    path: config
